In [1]:
import numpy as np

In [2]:
big_array = np.random.rand(10000000)
%timeit sum(big_array)

1 loop, best of 3: 876 ms per loop


In [4]:
import numpy as np
a = np.array([1, 2, 5, 7, 0, 8])

print(a)
print("Loai du lieu cua bien a:", type(a))
print("Kieu du lieu cua phan tu trong mang a:", a.dtype)
print("Kich thuoc cua mang a:", a.shape)
print("So phan tu cua mang a:", a.size)
print("So chieu cua mang a:", a.ndim)

[1 2 5 7 0 8]
('Loai du lieu cua bien a:', <type 'numpy.ndarray'>)
('Kieu du lieu cua phan tu trong mang a:', dtype('int64'))
('Kich thuoc cua mang a:', (6,))
('So phan tu cua mang a:', 6)
('So chieu cua mang a:', 1)


In [5]:
## khởi tạo mảng có sẵn trong numpy

In [6]:
np.zeros((3, 4))
# 3 dòng, 4 cột

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((2, 3, 4), dtype=np.int16)
# 2 mảng, 3 dòng, 4 cột

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [9]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
e = np.full((2, 2), 7)

In [13]:
e

array([[7, 7],
       [7, 7]])

In [14]:
f = np.eye(2)

In [15]:
f

array([[1., 0.],
       [0., 1.]])

In [16]:
np.random.random((2, 2))

array([[0.6986674 , 0.91266035],
       [0.8072001 , 0.77175006]])

In [17]:
np.empty((3, 2))

array([[ 0.00000000e+000, -3.11108568e+231],
       [ 6.93613773e-310,  6.93613375e-310],
       [ 6.93613352e-310,  6.93613372e-310]])